table forecast_monthly

	column month
		dataType: dateTime
		isHidden
		formatString: Long Date
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column scenario
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: scenario

		annotation SummarizationSetBy = Automatic

	column p10
		dataType: double
		isHidden
		formatString: 0.0%;-0.0%;0.0%
		summarizeBy: none
		sourceColumn: p10

		annotation SummarizationSetBy = Automatic

	column p50
		dataType: double
		isHidden
		formatString: 0.0%;-0.0%;0.0%
		summarizeBy: none
		sourceColumn: p50

		annotation SummarizationSetBy = Automatic

	column p90
		dataType: double
		isHidden
		formatString: 0.0%;-0.0%;0.0%
		summarizeBy: none
		sourceColumn: p90

		annotation SummarizationSetBy = Automatic

	partition forecast_monthly = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "forecast_monthly.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"month", type date}, {"scenario", type text}, {"p10", type number}, {"p50", type number}, {"p90", type number}})
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

