table forecast_annual
	lineageTag: a6b6773f-d4d0-4a58-a413-e000d9f24711

	column scenario
		dataType: string
		lineageTag: 488b1e03-0d52-4990-b8ef-a2882da3ceb3
		summarizeBy: none
		sourceColumn: scenario
		sortByColumn: scenario_order

		annotation SummarizationSetBy = Automatic

	column scenario_order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5d45c94e-34f8-4e79-9c30-937ea8de988a
		summarizeBy: none
		sourceColumn: scenario_order

		annotation SummarizationSetBy = Automatic

	column assumption
		dataType: string
		lineageTag: c907acb1-9b73-4216-b1e4-fd958b40e7a8
		summarizeBy: none
		sourceColumn: assumption

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: de93a0c2-53a0-4da2-b9aa-ee69ef470683
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column median
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2980e0f9-8e09-40fe-b95f-7872c22693b2
		summarizeBy: none
		sourceColumn: median

		annotation SummarizationSetBy = Automatic

	column p10
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 96a2db39-8e65-47c3-aa3b-e6cd3abfbf82
		summarizeBy: none
		sourceColumn: p10

		annotation SummarizationSetBy = Automatic

	column p90
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 68f126b3-bcb9-4c55-b980-a930484e7120
		summarizeBy: none
		sourceColumn: p90

		annotation SummarizationSetBy = Automatic

	column p2_5
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5a00698a-fca1-4655-b085-6f1a527ae8ac
		summarizeBy: none
		sourceColumn: p2_5

		annotation SummarizationSetBy = Automatic

	column p97_5
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 840cf0a4-1b58-4415-8a45-2e4cb8a520e8
		summarizeBy: none
		sourceColumn: p97_5

		annotation SummarizationSetBy = Automatic

	partition forecast_annual = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "forecast_annual.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"scenario", type text}, {"scenario_order", Int64.Type}, {"assumption", type text}, {"year", Int64.Type}, {"median", type number}, {"p10", type number}, {"p90", type number}, {"p2_5", type number}, {"p97_5", type number}})
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

