table regional_key_numbers
	lineageTag: 91e7b933-67fd-4cd7-8eae-d205e0c16e82

	column metric
		dataType: string
		lineageTag: 8666337e-b901-4fa1-af98-c4a6c3e2e7ee
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: 0.0
		lineageTag: 43c5bdcc-ffe5-41b4-9df8-6781ffc0d8ba
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: c3d9e047-f0cd-4b1d-bca6-e3833dfa5830
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: 071035d1-b2f3-48ee-a6a7-50c4c41b7110
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	partition regional_key_numbers = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "regional_key_numbers.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"metric", type text}, {"value", type number}, {"unit", type text}, {"note", type text}})
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

